"""doube3

Revision ID: 15a385fd42a
Revises: 1e46d1a84138
Create Date: 2015-10-24 16:55:02.651898

"""

# revision identifiers, used by Alembic.
revision = '15a385fd42a'
down_revision = '1e46d1a84138'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
