"""empty message

Revision ID: 3fe07c33ba77
Revises: 5429b2b4a7f3
Create Date: 2016-05-22 13:11:48.049541

"""

# revision identifiers, used by Alembic.
revision = '3fe07c33ba77'
down_revision = '5429b2b4a7f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
